pins_headers = {}

pins_headers['accept'] = '*/*'
pins_headers['accept-encoding'] = 'gzip, deflate, br'
pins_headers['accept-language'] = 'en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,ja;q=0.6'
pins_headers['origin'] = 'https://www.zhihu.com'
pins_headers['referer'] = 'https://www.zhihu.com/'
pins_headers['user-agent'] = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'
pins_headers['x-ab-param'] = 'tp_ios_topic_write_pin_guide=1;top_billvideo=0;top_dtmt=2;top_followtop=1;top_retagg=0;top_topic_feedre=21;top_cc_at=1;top_hweb=0;top_billpic=0;top_mlt_model=0;top_recall_tb_long=51;top_no_weighing=1;top_nuc=0;se_consulting_switch=off;top_feedre_cpt=101;top_hca=0;top_root=1;se_rescore=1;top_ab_validate=0;top_sjre=0;top_tag_isolation=0;se_new_market_search=on;top_card=-1;top_feedtopiccard=0;top_vd_op=1;se_merger=1;se_ingress=on;top_multi_model=0;top_vd_gender=1;top_video_fix_position=0;top_f_r_nb=1;se_auto_syn=0;se_dt=1;se_gemini_service=knowledge;top_recall_core_interest=81;top_test_4_liguangyi=1;zr_ans_rec=gbrank;top_recommend_topic_card=0;top_v_album=1;top_spec_promo=1;top_vdio_rew=0;top_root_ac=1;top_video_score=1;top_yc=0;tp_discussion_feed_card_type=0;top_fqa=0;top_promo=1;top_local=1;top_feedre_rtt=41;top_tagore=1;top_tagore_topic=0;top_free_content=-1;top_nucc=3;tp_discussion_feed_type_android=0;se_correct_ab=0;top_roundtable=1;tp_write_pin_guide=3;pin_ef=orig;se_major_onebox=major;top_distinction=0;top_gr_auto_model=0;top_ntr=1;top_universalebook=1;top_user_gift=0;top_sj=2;top_hqt=9;top_login_card=1;top_tffrt=0;top_30=0;top_billread=1;top_retag=0;ls_play_continuous_order=2;top_pfq=0;top_yhgc=0;top_root_mg=1;top_vds_alb_pos=0;top_gr_model=0;top_is_gr=0;top_recall_deep_user=1;se_gi=0;top_recall_tb=5;top_gr_topic_reweight=0;se_wiki_box=1;top_feedre=1;top_keyword=0;se_minor_onebox=d;top_ebook=0;top_newfollowans=0;top_nszt=0;top_vd_score_new=2;top_nmt=0;top_recall_tb_short=61;se_relevant_query=old;top_adpar=0;top_bill=0;se_product_rank_list=0;se_dl=0;top_root_web=0;top_video_rew=0;top_quality=0;tp_sft=a;top_gif=0;top_memberfree=1;top_recall_tb_follow=71;top_root_few_topic=0;top_ad_slot=1;top_billab=1;top_tr=1;top_videos_priority=-1;se_daxuechuisou=new;top_rank=8;top_recall_follow_user=91;se_entity=on;top_billupdate1=3;top_slot_ad_pos=3;top_follow_question_hybrid=0;top_billboard_count=1;top_new_user_gift=0;top_recall=1;top_manual_tag=1;top_fqai=0;top_keywordab=0;top_raf=n;se_refactored_search_index=0;se_tf=1;top_uit=0;top_lowup=1;top_newfollow=0;se_consulting_price=n;top_nid=0;pin_efs=orig;se_cm=0;top_tmt=0;ls_new_video=0;top_an=0;top_nad=1;top_ac_merge=0;top_alt=0;top_feedre_itemcf=31;top_follow_reason=0'
pins_headers['x-requested-with'] = 'fetch'
pins_headers['x-udid'] = 'AJDmokHXcA6PTr3wb7f_TClBiH556XOMr0w='
pins_headers['x-xsrftoken'] = '5311b42d-d4de-4fca-a10d-e46bf6cb6169'
